const Detections = [
    { detection: "person" },
    { detection: "bicycle" },
    { detection: "motorbike" },
    { detection: "aeroplane" },
    { detection: "bus" },
    { detection: "train" },
    { detection: "truck" },
    { detection: "boat" },
    { detection: "traffic light" },
    { detection: "car" },
    { detection: "fire hydrant" },
    { detection: "stop sign" },
    { detection: "parking meter" },
    { detection: "bench" },
    { detection: "bird" },
    { detection: "cat" },
    { detection: "dog" },
    { detection: "horse" },
    { detection: "sheep" },
    { detection: "cow" },
    { detection: "elephant" },
    { detection: "bear" },
    { detection: "zebra" },
    { detection: "giraffe" },
    { detection: "backpack" },
    { detection: "umbrella" },
    { detection: "handbag" },
    { detection: "tie" },
    { detection: "suitcase" },
    { detection: "frisbee" },
    { detection: "skis" },
    { detection: "snowboard" },
    { detection: "sports ball" },
    { detection: "kite" },
    { detection: "baseball bat" },
    { detection: "baseball glove" },
    { detection: "skateboard" },
    { detection: "surfboard" },
    { detection: "tennis racket" },
    { detection: "bottle" },
    { detection: "wine glass" },
    { detection: "cup" },
    { detection: "fork" },
    { detection: "knife" },
    { detection: "spoon" },
    { detection: "bowl" },
    { detection: "banana" },
    { detection: "apple" },
    { detection: "sandwich" },
    { detection: "orange" },
    { detection: "broccoli" },
    { detection: "carrot" },
    { detection: "hot dog" },
    { detection: "pizza" },
    { detection: "donut" },
    { detection: "cake" },
    { detection: "chair" },
    { detection: "sofa" },
    { detection: "potted plant" },
    { detection: "bed" },
    { detection: "dining table" },
    { detection: "toilet" },
    { detection: "tvmonitor" },
    { detection: "laptop" },
    { detection: "mouse" },
    { detection: "remote" },
    { detection: "keyboard" },
    { detection: "cell phone" },
    { detection: "microwave" },
    { detection: "oven" },
    { detection: "toaster" },
    { detection: "sink" },
    { detection: "refrigerator" },
    { detection: "book" },
    { detection: "clock" },
    { detection: "vase" },
    { detection: "scissors" },
    { detection: "teddy bear" },
    { detection: "hair drier" },
    { detection: "toothbrush" }
]

export default Detections